hiring/urls.py
from django.conf.urls import url
from .views import *
from django.views.generic.base import TemplateView

app_name='hiring'
urlpatterns = [
    url(r'^$',home,name='home'),
    url(r'^signup/$',signup,name='signup'),
    url(r'^login/$',userlogin,name='login'),
    url(r'^emailsent/$',  TemplateView.as_view(template_name="emailsent.html"), name="emailsent"),
    url(r'^event(?P<pk>[0-9]+)/calender/$',  calenderview, name="calender"),
    url(r'^afterverification/(?P<token>.*)/$', afterverify, name="afterverification"),
    url(r'^logout/$',userlogout,name='logout'),
    url(r'^events/$',showevents,name='events'),
    url(r'^event(?P<pk>[0-9]+)/$',showevent,name='event'),
    url(r'^register/(?P<events_id>[0-9]+)/(?P<key>[0-9]+)/(?P<start_date>[^/]+)/(?P<start_time>[^/]+)/$',register,name = 'register'),
    url(r'^agree/(?P<pk>[0-9]+)/$',agree,name='agree'),
    url(r'^test/(?P<pk>[0-9]+)/$',test,name='test'),
    url(r'^question/(?P<pk>[0-9]+)/$',question,name='question'),
    url(r'^solution/(?P<pk>[0-9]+)/(?P<testpk>[0-9]+)/$',solution,name='solution'),
    url(r'^save/(?P<pk>[0-9]+)/(?P<testpk>[0-9]+)/$',next,name='save'),

]

myproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hiring/', include('hiring.urls')),

]

hiring/models.py
from django.db import models
from django.contrib.auth.models import User


def upload_image(instance,filename):
	return "cv/%s/%s"%(instance.id,filename)

def uploadcv(instance,filename):
	return "cv/%s/%s"%(instance.id,filename)

class Profile(models.Model):
	m='male'
	f='female'
	gender=((m,'male'),
		(f,'female'))
	user= models.OneToOneField(User,related_name='profile')
	first_name=models.CharField(max_length=50)
	last_name=models.CharField(max_length=50)
	dob=models.DateField(auto_now=False,auto_now_add=False)
	gender=models.CharField(max_length=15,choices=gender)
	photo=models.ImageField(upload_to=upload_image,null=True,height_field='height', width_field='width',blank=True)
	height=models.IntegerField(default=0)
	width=models.IntegerField(default=0)
	skills=models.TextField()
	cv=models.FileField(upload_to=uploadcv,null=True,blank=True)
	def __str__(self):
		return self.first_name+" "+self.last_name

class Token(models.Model):
	user=models.OneToOneField(User,related_name='token')
	token=models.CharField(max_length=300,null=True)


class Events(models.Model):
	i='Internship'
	f='Full-Time'
	p='Part-Time'
	job_type=((i,'Internship'),(f,'Full-Time'),(p,'Part-Time'))
	posted_on=models.DateField(auto_now=False, auto_now_add=True)
	name=models.CharField(max_length=100,verbose_name="Event Name")
	type_job=models.CharField(max_length=20,choices=job_type)
	vacancies=models.IntegerField(default=0)
	desc=models.TextField()
	time_duration=models.IntegerField(default=0)
	salary=models.CharField(max_length=50,default='Based on performance')
	end_date=models.DateField(auto_now=False, auto_now_add=False)
	def __str__(self):
		return self.name



class Datetime(models.Model):
	event=models.ForeignKey(Events,on_delete=models.CASCADE,related_name='date')
	date=models.DateField(auto_now=False, auto_now_add=False)
	time=models.TimeField(auto_now=False, auto_now_add=False)

class Exam(models.Model):
	profile=models.ForeignKey(Profile)
	event=models.ForeignKey(Events,on_delete=models.CASCADE)
	start_date=models.DateField(auto_now=False, auto_now_add=False)
	start_time=models.TimeField(auto_now=False, auto_now_add=False)
	registered=models.BooleanField(default=False)

def upload(instance,filename):
	return "files/"
class Test(models.Model):
	category=models.CharField(max_length=100)
	answer_files=models.FileField(blank=True)
	def __str__(self):
		return self.category

class Questions(models.Model):
	test=models.ForeignKey(Test,related_name='question')
	question=models.TextField()
	subjective=models.BooleanField(default=False)
	cc=models.CharField(max_length=10,blank=True)
	def __str__(self):
		return self.question

class Answer(models.Model):
	question=models.ForeignKey(Questions,related_name='answers')
	choice=models.CharField(max_length=300,blank=True)
	text=models.TextField(blank=True)
	

hiring/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.extras.widgets import SelectDateWidget
from  .models import *
from django.contrib.auth import authenticate


class UserCreationForm(UserCreationForm):
	email=forms.EmailField(required=True)

	class Meta:
		model=User
		fields=['username','email','password1','password2']

	def clean_email(self):
		data = self.cleaned_data['email']
		if User.objects.filter(email=data).exists():
			raise forms.ValidationError("This email already exists.")
		return data

	def save(self, commit=True):
		user = super(UserCreationForm, self).save(commit=False)
		user.email = self.cleaned_data["email"]
		if commit:
			user.save()
		return user	
class Userform(forms.ModelForm):
	class Meta:
		model=Profile
		exclude=('user','email','height','width')
		widgets = {
            'dob': forms.widgets.DateInput(attrs={'type': 'dob'}),
            }
class Loginform(forms.Form):
	username=forms.CharField(required=True)
	password=forms.CharField(widget=forms.PasswordInput)

	def clean(self,*args,**kwargs):
		username=self.cleaned_data.get('username')
		password=self.cleaned_data.get('password')
		user=authenticate(username=username,password=password)
		if username and password:
			if not user:
				raise forms.ValidationError("User doesn't exists")
			if not user.check_password(password):
				raise forms.ValidationError("password is incorrect")
			if not user.is_active:
				raise forms.ValidationError('User is not active')
			return super(Loginform,self).clean(*args,**kwargs)
class Eventform(forms.ModelForm):
	class Meta:
		model=Events
		fields=['name','desc']

hiring/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.contrib.auth import logout,login,authenticate
from django.core.mail import send_mail
from base64 import b64encode
from os import urandom
from .models import *
from .forms import *
from django.views.generic import DetailView
from django.http import HttpResponse
import  datetime
from django.core.files.base import ContentFile
from random import randint
from django.core.files.base import ContentFile
from django.conf import settings



# Create your views here.
def home(request):
	title='startxlabs Recruitement Home'
	context={
	'title':title
	}
	return render(request,'hiring/home.html',context)

def signup(request):
	title='Signup Page'
	if request.user.is_active:
		logout(request)

	user_form = UserCreationForm()

	if request.method == 'POST':
		user_form = UserCreationForm(request.POST)
		if user_form.is_valid():
				u = user_form.save(commit=False)
				u.is_active = False
				u.save()
				random_bytes = urandom(25)
				token = b64encode(random_bytes).decode('utf-8')
				tokenobj=Token.objects.create(user_id=u.id)
				tokenobj.token=token
				tokenobj.save()
				subject = "Email Verification"
				email=user_form.cleaned_data.get('email')
				message = "Please click on this link to verify your email address : \" http://127.0.0.1:8000/hiring/afterverification/%s \" " %(token)
				recipient_list = [email]
				from_email = 'startxlabstestuser@gmail.com'
				send_mail(subject,message,from_email,recipient_list)
				return redirect('/hiring/emailsent/')	
		# print vars(user_form)
	context={
	'title':title,
	'user_form':user_form,

	}
	return render(request,'hiring/signup.html',context)


def afterverify(request,token):
	title='Email Verification'
	try:
		usernow = Token.objects.get(token=token)
	except User.DoesNotExist:
		error(request,"Invalid user.Please check the link again.")
		return redirect('hiring:home')
	usernew = User.objects.get(id=usernow.user.id)
	form = Userform()
	if request.method =='POST':
		form=Userform(request.POST ,request.FILES)
		if form.is_valid():
			u=form.save(commit=False)
			first=form.cleaned_data.get('first_name')
			last=form.cleaned_data.get('last_name')
			dob=form.cleaned_data.get('dob')
			gender=form.cleaned_data.get('gender')
			image=form.cleaned_data.get('photo')
			cv=form.cleaned_data.get('cv')
			usernew.is_active=True
			usernew.save()
			usernow.applied = True
			usernow.delete()
			obj=Profile.objects.create(user_id=usernew.id,first_name=first,last_name=last,dob=dob,gender=gender,photo=image,cv=cv)
			return redirect('hiring:home')
			
	context={
	'title':title,
	'form':form

	}
	return render(request,'hiring/afterv.html',context)
def userlogin(request):
	title='Login page'
	form=Loginform(request.POST or None)
	if form.is_valid():
		username=form.cleaned_data.get('username')
		password=form.cleaned_data.get('password')
		user=authenticate(username=username,password=password)
		login(request,user)
		print (request.user.is_authenticated)
		return redirect('hiring:home')
	context={
	'title':title,
	'form':form
	}
	return render(request,'hiring/login.html',context)
def userlogout(request):
	logout(request)
	return render(request,'hiring/logout.html',{})

def showevents(request):
	title='Events'
	all_events=Events.objects.all()
	context={
	'title':title,
	'all_events':all_events
	}
	return render(request,'hiring/events.html',context)


def showevent(request,pk):
	event=Events.objects.get(pk=pk)
	title=event.name
	date = datetime.datetime.today().date()
	time = datetime.datetime.now().time()
	# print (time)
	delta=datetime.timedelta(minutes=event.time_duration)
	# print (delta)
	try:
		exam = Exam.objects.get(profile = request.user.profile,event=event)
		end_time=(datetime.datetime.combine(datetime.datetime.today().date(),exam.start_time)+delta).time()
		print time >= exam.start_time
		print end_time >= time
	except:
		exam=None
		end_time=datetime.datetime.now().time()
	context={
	'title':title,
	'events':event,
	'exam':exam,
	'date':date,
	'time':time,
	'end_time':end_time,
	}
	return render(request,'hiring/event.html',context)

@login_required(login_url='/hiring/login/')
def calenderview(request,pk):
	event=Events.objects.get(id=pk)
	date = Datetime.objects.filter(event__id = pk)
	profile=Profile.objects.get(user_id=request.user.id)

	context={
	'event':event,
	'date':date,
	'profile':profile,
	}
	return render(request,'hiring/calender.html',context)

@login_required(login_url='/hiring/login/')
def register(request,events_id,key,start_date,start_time):
	title='Register for the Event'
	profile=Profile.objects.get(id=key)
	event=Events.objects.get(id=events_id)
	name=event.name
	date=start_date
	time=start_time
	salary=event.salary	
	if request.method=='POST':
		exam=Exam.objects.create(profile=profile,event=event,start_date=start_date,start_time=start_time,registered=True)
		subject = "Email Verification"
		email=request.user.email
		message ="you have registered for the test"
		recipient_list = [email]
		from_email = 'startxlabstestuser@gmail.com'
		send_mail(subject,message,from_email,recipient_list)
		return redirect('hiring:home')
	context={
	'title':title,
	'name':name,
	'date':date,
	'time':time,
	'salary':salary,
	}		
	return render(request,'hiring/register.html',context)


@login_required(login_url='/hiring/login/')
def agree(request,pk):
	exam=Exam.objects.get(pk=pk)
	context={
	'exam':exam
	}
	return render(request,'hiring/agree.html',context)

@login_required(login_url='/hiring/login/')
def test(request,pk):
	exam=Exam.objects.get(pk=pk)
	name=exam.event.name
	test=Test.objects.filter(category=name)
	title="Test"
	i=randint(0,len(test)-1)
	questions=test[i]
	j=questions.pk
	k=questions.question.first().pk
	context={
	'qid':j,
	'questions':questions,
	'id':k,
	'title':title
	}
	return render(request,'hiring/test.html',context)

def question(request,pk):
	test=Test.objects.get(pk=pk)
	context={
	'test':test,
	}
	return render(request,'hiring/Questionframe.html',context)
import os
def solution(request,pk,testpk):
	BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	file_path = os.path.join(os.path.dirname(BASE_DIR),"media_cdn")
	obj=Test.objects.get(pk=testpk)
	question=Questions.objects.get(pk=pk)
	cat = '_'.join(obj.category.split())
	data = dict()
	if request.method == 'POST':
		old_text = ''
		print file_path+'/'+request.user.username+'/'+obj.category+'.txt'
		if os.path.exists(file_path+'/'+request.user.username+'/'+cat+'.txt'):
			with open(file_path+'/'+request.user.username+'/'+cat+'.txt', 'r') as file:
				old_text = file.read() + '\n'
				os.remove(file_path+'/'+request.user.username+'/'+cat+'.txt')
		data = request.POST.dict()
		try:
			print data.get('choice')
			text=question.question+" , "+data['choice']+" , "+question.cc
			content = ContentFile(old_text+text)
		except:
			text=question.question+" "+data['answer']
			content=ContentFile(old_text+text)
		obj.answer_files.save(file_path+'/'+request.user.username+'/'+cat+'.txt', content)
		obj.save()
	context={
	'question':question,
	'test':obj,
	'abc':obj.id,
	'data':data.get('choice') or data.get('answer')
	}
	return render(request,'hiring/solutionframe.html',context)



	

hiring/templates/hiring/Questionframe.html
<!Doctype HTML>
<html>
	<head>
	</head>
	<body>
		{% for q in test.question.all %}
		<ul>
			<li><a href="{% url 'hiring:solution' q.pk test.id %}"  target="solution">{{ q.question }}</a></li>
		</ul>
		{% endfor %}
	</body>
</html>

hiring/templates/hiring/afterv.html
<form action='' method='POST' enctype='multipart/form-data' >
	{% csrf_token %}
	{{ form.as_p }}
	<input type='submit' value='submit' />
</form>

hiring/templates/hiring/agree.html
<p style=" font-weight: bold;">
	Details Regarding Test<br/>
	<input type="checkbox" id="termsChkbx " onclick="change_button(this,'sub1')"/>
	I have read and agree to the terms and conditions
</p>
<p><a href="{% url 'hiring:test' exam.pk %}"><input type="submit" name="submit" value="I Understand" id="sub1" disabled="disabled"/></a></p>

<script type = "text/javascript">
function change_button(checkbx,button_id) {
    var btn = document.getElementById(button_id);
    if (checkbx.checked == true) {
        btn.disabled = "";
    } else {
        btn.disabled = "disabled";
    }
}
</script>

hiring/templates/hiring/calender.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<link rel='stylesheet' href="{% static 'js/lib/cupertino/jquery-ui.min.css' %}" />
<link href="{% static 'css/fullcalendar.min.css' %}" rel='stylesheet' />
<link href="{% static 'css/fullcalendar.print.min.css' %}" rel='stylesheet' media='print' />
<script src="{% static 'js/lib/moment.min.js' %}"></script>
<script src="{% static 'js/lib/jquery.min.js' %}"></script>
<script src="{% static 'js/fullcalendar.min.js' %}"></script>
<script type="text/javascript">
var utc = new Date().toJSON().slice(0,10).replace(/-/g,'/');
    $(document).ready(function() {

        $('#calendar').fullCalendar({
        
            theme: true,
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay,listMonth'
            },          
            
            defaultDate: moment(utc),
            navLinks: true, // can click day/week names to navigate views
            editable: false,
            eventLimit: true, // allow "more" link when too many events
            events: [
                
                {% for i in date.all %}
                {
                    start: '{{ i.date|date:'c'}}T{{i.time|date:'c' }}',
                    url: "{%  url 'hiring:register' events_id=event.id key=profile.id start_date=i.date start_time=i.time  %}",
                
                },
                {% endfor %}
    
      
            ]
        });
        
    });

</script>
<style>

	body {
		margin: 40px 10px;
		padding: 0;
		font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
		font-size: 14px;
	}

	#calendar {
		max-width: 900px;
		margin: 0 auto;
	}

</style>
</head>
<body>

	<div id='calendar'></div>

</body>
</html>

hiring/templates/hiring/event.html
<p>{{ events.name }}</p>
<p>{{ events.vacancies }}</p>
<p>{{ events.type_job }}</p>
<p>{{ events.desc }}</p>
<p>{{ events.time }}</p>
{% if exam.registered %}
{% if ( exam.start_date == date  and time >= exam.start_time and end_time >= time ) or (time==time)   %}
	<button name='button' type='button'><a href="{% url 'hiring:agree' pk=exam.id %}">Start Now</a></button>
{% else %}
<p>Registered</p>
{% endif %}
{% else %}
<button name="button" type="button"><a href="{% url 'hiring:calender' pk=events.id %}">Register</a></button> 
{% endif %}

hiring/templates/hiring/events.html
{{ request.user }}
<ul>
	{% for event in all_events %}
		<li> <a href="{% url 'hiring:event' event.id %}">{{ event.name }}</a></li>
	{% endfor %}
</ul>

hiring/templates/hiring/home.html
{% load staticfiles %}
<!Doctype HTML>
<html>
	<head>
		<title>{{ title }}</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link href='{% static "img/favicon.png" %}' rel='shortcut icon'>
	</head>
	<body>
		<nav class='navbar navbar-inverse navbar-fixed-top'>
			<div class='container'>
				<div class='clearfix'>
					<div class='col-md-1'></div>
					<div class='col-md-10 col-sm-12 col-xs-12'>
						<div class='navbar-header headerlink'>
							<button aria-expanded='false' class='navbar-toggle collapsed' data-target='#header-navbar-collapse' data-toggle='collapse' type='button'>
								<span class='sr-only'>Toggle navigation</span>
								<span class='icon-bar'></span>
								<span class='icon-bar'></span>
								<span class='icon-bar'></span>
							</button>
							<a class='navbar-brand' href='{% url "hiring:home" %}'>
								<img alt="Startxlabslogo" src="{% static 'img/startxlabslogo.png' %}" />
							</a>
						</div>
						<div aria-expanded='false' class='navbar-collapse collapse' id='header-navbar-collapse' style='height: 1px;'>
							<ul class='nav navbar-nav navbar-right'>
								<li ><a  href='{% url "hiring:home" %}'>Home</a></li>
								<li ><a href="{% url 'hiring:events'%}">Events</a></li>
								{% if request.user.is_authenticated %}
								<li>Hello {{ request.user }}</li>
								{% else %}
								<li ><a href="{% url 'hiring:login' %}">Sign Up/Log In</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				<div class='col-md-1'></div>
				</div>
			</div>
		</nav>
		{% block content %}
		{% endblock %}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
		<script type="text/javascript">
			$(document).keydown(function(event)
			{
			    if(event.keyCode==123){  //Prevent from f12
			    return false;
			   }
				else if(event.ctrlKey && event.shiftKey && event.keyCode==73){        
				      return false;  //Prevent from ctrl+shift+i
				   }
				   
				else if(event.keyCode==116){ //Prevent from f5
				    return false;
				   }
				else if(event.keyCode==122){ //Prevent from f11
				    return false;
				   }   
			});
</script>
	</body>
</html>

hiring/templates/hiring/login.html
{% extends 'hiring/home.html' %}
{% block content %}
	<div class="container" style="padding-top: 70px; " >
		<div class="row">
			<div class="col-md-offset-4 col-md-4 text-center" >
				<label for="email">LOGIN HERE </label>
			</div>				
		</div>
		<br>
		<div class="row">
			<div class="col-md-offset-4 col-md-4" style="border: 1px solid grey;border-radius: 15px; padding: 30px;">
			<center>
				<form action='' method='POST'>
				{% csrf_token %}
				{{ form.as_p }}
				<input type='submit' value='submit' class="btn btn-default" />
				</form>
				</center>
		</div>	
		<div class="col-md-offset-4 col-md-4 text-center" >Need an account <a href="{% url 'hiring:signup' %}">Sign Up</a> here</div>			
		</div>
		
	</div>
{% endblock %}

hiring/templates/hiring/register.html
<p>{{name}}</p>
<p>{{date}}</p>
<p>{{time}}</p>
<p>{{salary}}</p>
<form action="" method='POST' >
	{% csrf_token %}
	<input type="submit" value='submit' />
</form>

hiring/templates/hiring/signup.html
{% extends 'hiring/home.html' %}
{% block content %}
<style type="text/css">
body{
    background-color: #525252;
}
.centered-form{
	margin-top: 60px;
}

.centered-form .panel{
	background: rgba(255, 255, 255, 0.8);
	box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
}
</style>
<div class="container">
    <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    	<h3 class="panel-title">Please Sign Up Here</h3>
			 		</div>
			 		<div class="panel-body">
			    	<form role="form" method='POST' action="">
			    		{% csrf_token %}
			    		
		    			<div class="form-group">
		    				{{ user_form.username.errors }}
		    				<input type="text" name="username" id='{{ user_form.username }}' class="form-control input-sm" placeholder="Username">
		    			</div>
		    		
		    		{{ user_form.email.errors }}
			    		<div class="form-group">
			    			<input type="email" name='email' id='{{ user_form.email }}' class="form-control input-sm" placeholder="Email Address">
			    		</div>
		    		
			    		{% for error in user_form.non_field_errors %}
    						{{error}}
						{% endfor %}
			    		<div class="row">
			    			<div class="col-xs-6 col-sm-6 col-md-6">
			    				{{ user_form.password1.errors }}
			    				<div class="form-group">
			    					<input type="password" name='password1' id='{{ user_form.password1 }}' class="form-control input-sm" placeholder="Password">
			    				</div>
			    			</div>
			    			<div class="col-xs-6 col-sm-6 col-md-6">
			    				{{ user_form.password2.errors }}
			    				<div class="form-group">
			    					<input type="password" name='password2' id='{{ user_form.password2 }}' class="form-control input-sm" placeholder="Confirm Password">
			    				</div>
			    			</div>
			    		</div>
			    		<input type="submit" value="Register" class="btn btn-info btn-block">
			    	</form>
			    </div>
	    	</div>
    	</div>
    </div>
</div>
{% endblock %}

hiring/templates/hiring/solutionframe.html
{% load staticfiles %}
{% load hiring_extras %}
<!Doctype HTML>
<html>
	<head>
		<title>{{ title }}</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link href='{% static "img/favicon.png" %}' rel='shortcut icon'>
	</head>
	<script type="text/javascript">
	$('textarea').keypress(function(event) {
	   if (event.which == 13) {
	      event.preventDefault();
	      var s = $(this).val();
	      $(this).val(s+"\n");
	   }
	});​
	</script>

<body>
<h1>{{ question.question }}</h1>
<form action="" method='POST' enctype='multipart/form-data' >
{% csrf_token %}
<ul>
	{% if question.subjective %}
	<p align='left'>Answer:</p><textarea name="answer" style="margin: 0px; width: 700px; height: 500px;">
	{% if data  %} {{data}} {% endif %}
</textarea><br/>
	{% else %}
	{% for choice in question.answers.all %}
	<p>{{ forloop.counter }}.<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ forloop.counter }}" {% if forloop.counter == data|add:0  %} checked="checked" {% endif %}/>
    <label for="choice{{ forloop.counter }}">{{ choice.choice }}</label><br />
	{% endfor %}
	{% endif %}
	</p>
</ul>
	<div align='right'>
		{% for i in test.question.all %}
		{% if i.id == question.id %}
		<button type="button"><a href="{% url 'hiring:solution' abc|previous:i.id test.id %}" >Previous</a></button>{% endif %}
		{% endfor %}
		<input type='submit' value='save'>
		{% for i in test.question.all %}
		{% if i.id == question.id %}
		<button type="button"><a href="{% url 'hiring:solution' abc|next:i.id test.id %}" id='next'>Next</a></button>{% endif %}
		{% endfor %}
	</div>
</form>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
		<script type="text/javascript">
			$(document).keydown(function(event)
			{
			    if(event.keyCode==123){  //Prevent from f12
			    return false;
			   }
				else if(event.ctrlKey && event.shiftKey && event.keyCode==73){        
				      return false;  //Prevent from ctrl+shift+i
				   }
				   
				else if(event.keyCode==116){ //Prevent from f5
				    return false;
				   }
				else if(event.keyCode==122){ //Prevent from f11
				    return false;
				   }   
			});;
	</script>
</body>
</html>

hiring/templates/hiring/test.html
{% load staticfiles %}
<!Doctype HTML>
<html>
	<head>
		<title>{{ title }}</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<link href='{% static "img/favicon.png" %}' rel='shortcut icon'>
	</head>
<frameset cols="28%,72%">
   <frame  src="{% url 'hiring:question' qid %}" />
   <frame name="solution" src="{% url 'hiring:solution' id qid %}" />
   <noframes>
   <body>
      <p>Use laptop or a desktop</p>
   </body>
   </noframes>
</frameset>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>
		<script type="text/javascript">
			$(document).keydown(function(event)
			{
			    if(event.keyCode==123){  //Prevent from f12
			    return false;
			   }
				else if(event.ctrlKey && event.shiftKey && event.keyCode==73){        
				      return false;  //Prevent from ctrl+shift+i
				   }
				   
				else if(event.keyCode==116){ //Prevent from f5
				    return false;
				   }
				else if(event.keyCode==122){ //Prevent from f11
				    return false;
				   }   
			});
	</script>
</html>